services:
  server:
    container_name: secuscan-back
    build:
      context: ../../api
      dockerfile: Dockerfile
    environment:
      MONGODB_URI: mongodb://root:example@mongo:27017/
      MONGO_DBNAME: secuscan
